feeds:
  - https://www.reuters.com/markets/rss
  - https://www.federalreserve.gov/feeds/press_all.xml
  - https://www.bls.gov/feed/news.rss
  - https://www.treasury.gov/resource-center/presscenter/press-releases/Pages/rss.aspx

keywords:
  must_have_any:
    - treasury
    - yield
    - curve
    - fed
    - inflation
    - cpi
    - pce
    - payrolls
    - ism
    - credit
    - spread
    - downgrade
    - default
    - mortgage
    - rates
    - auction

stop_words:
  - celebrity
  - sports
  - entertainment

sentiment_overrides:
  positive:
    - rally
    - beat
    - easing
    - strong
    - tightens_spreads
    - disinflation
  negative:
    - selloff
    - slump
    - spike
    - surge
    - downgrade
    - default
    - sticky_inflation
